# Path del modelo preentrenado
# -*- coding: utf-8 -*-
""" app.ipynb

Automatically generated by Colaboratory.

Original file is located at
https://colab.research.google.com/drive/15fzUs4bQMARyboMEzhCtg0wQ4kJcQxcN
"""
import streamlit as st
from utils import *

st.set_page_config(page_icon="📊", page_title="PREDICCIÓN DEL PRECIO PROMEDIO DEL AGUACATE EN EE.UU.", layout="wide")
   
col1, col2, col3 = st.columns([1, 4, 1])

def main():
    
    model=''

#Se carga el modelo
    if model=='':
       model = joblib.load(MODEL_PATH) # Carga del modelo.

    with col1:
       st.image("logo.png", width=160)
       st.sidebar.markdown('# **Proyecto Elaborado por:**')
       st.sidebar.markdown('### **Emiliano Rodriguez**' )
       st.sidebar.markdown('### **Javier Hernan Gil Gómez**')

    with col2:
       st.title("PREDICCIÓN DEL PRECIO PROMEDIO DEL AGUACATE EN EE.UU ")   
       predictS=""
       uploaded_file = st.file_uploader("Carga un archivo .csv con el historico de precios de las anteriores semanas", type = 'csv', key="1", )
       
       #El botón predicción se usa para iniciar el procesamiento

       if st.button("Oprime para realizar la predicción"):
          predictS = model_prediction(uploaded_file, model)
          st.success('El precio promedio del aguacate en la próxima semana según el historico ingresado es : {} dólares'.format(predictS[0].round(decimals =3)))

#El usuario carga un archivo .csv
    if uploaded_file is not None:
       file_container = st.expander("Verifique el archivo .CSV que acaba de subir")

          
if __name__ == '__main__':
    main()
